api/urls.py
from django.urls import path
from rest_framework.serializers import as_serializer_error
from .views import *
app_name = "api"

urlpatterns = [
    path('ticket/',TicketList.as_view(),name="list"),
    path('ticket/<int:pk>/',TicketDetail.as_view(),name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from account import views
from django.contrib.auth.views import  LogoutView
from config.settings import DEBUG
from django.conf import settings   
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Ticket
    path('ticket/', include('ticket.urls')),
    #Api
    path('api/', include('api.urls')),
    #Account
    path('account/', include('account.urls')),
    path('login/', views.Login, name="login"), 
    path('logout/', LogoutView.as_view(), name='logout'), 
    path('signup/', views.Signup, name="signup"),
]


if DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from . import views

app_name='ticket'

urlpatterns = [
    
    path('', views.Home, name="homepage"),
    # Ticket
    path('add/', views.AddTicket, name="ticket-add"),
    path('list/', views.TicketList, name="ticket-list"),
    path('detail/<int:id>', views.TicketDetail, name="ticket-detail"),
    # Response
    path('response/<int:id>', views.AddResponse, name="response-add"),

]

ticket/models.py
from django.db import models
from account.models import Department, User 
from datetime import datetime
from django.utils.translation import gettext as _
from extensions.utils import jalali_converter
# Create your models here.


class Ticket(models.Model):
    
    user = models.ForeignKey(User, verbose_name=_("کاربر"),default=None, on_delete=models.CASCADE)
    title = models.CharField(_("موضوع"), max_length=50)
    sup_type = models.ForeignKey(Department, verbose_name= _("دپارتمان"), on_delete=models.SET_NULL, blank=True,null=True)
    content = models.TextField(_("پیام"),blank=True,null=True)
    image = models.ImageField(_("عکس"), upload_to='media/ticket',blank=True,null=True)
    pb_date = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=False, default=datetime.now)
    status = models.BooleanField(_("وضعیت تیکت"),default=True)
    
    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"
        ordering = ['-pb_date']

    def __str__(self):
        return self.title
    def jpublish(self):
        return jalali_converter(self.pb_date)
    jpublish.short_description = "زمان انتشار"

class Response(models.Model):
    user = models.ForeignKey(User, verbose_name=_("کاربر"),default=None, on_delete=models.CASCADE)
    ticket = models.ForeignKey("Ticket", verbose_name=_("تیکت"),default=None, on_delete=models.CASCADE)
    content = models.TextField(_("پیام"),blank=True,null=True)
    image = models.ImageField(_("عکس"), upload_to='media/ticket',blank=True,null=True)
    pb_date = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=False, default=datetime.now)
    
    class Meta:
        verbose_name = "جواب"
        verbose_name_plural = "جواب ها"
        ordering = ['-pb_date']

    def jpublish(self):
        return jalali_converter(self.pb_date)
    jpublish.short_description = "زمان انتشار"
    

    def __str__(self):
        return self.content

ticket/forms.py
from django.db.models import fields
from django.db.models.base import Model
from .models import Ticket, Response
from django.forms import ModelForm
# class TicketForm(forms.Form):
#     STATUS_CHOICES = (
# 		('d', 'پشتیبانی'),
# 		('p', "حسابداری"),
# 	)
#     title = forms.CharField(label='Your name', max_length=100,required=True)
#     sup_type = forms.ChoiceField(choices=STATUS_CHOICES)
#     email = forms.EmailField(disabled=True,max_length=100, required=False)
#     content = forms.CharField(widget=forms.Textarea,required=True)


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        exclude = ['pb_date', 'status', 'user', 'response']


class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = ['content', 'image', ]

ticket/views.py
from django.shortcuts import render,redirect
from .models import Ticket, Response
from account.models import Department
from .forms import TicketForm,ResponseForm
from django.contrib.auth.decorators import login_required


@login_required
def Home(request):
    context = {}
    return render(request,'ticket/home.html',context)

'''لیست تیکت های کاربر یا پشتیبان'''
@login_required
def TicketList(request):    
    ticket_list = Ticket.objects.all()
    cus_tickets = Ticket.objects.filter(user=request.user)
    
    if request.user.is_supporter:
        sup_tickets = Ticket.objects.filter(sup_type=request.user.department)

    context = {
        'ticket_list': ticket_list,
        'sup_tickets':sup_tickets,
        'cus_tickets':cus_tickets,
    }
    return render(request,'ticket/list.html',context)


@login_required
def AddTicket(request):      
    departments = Department.objects.all()
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect("ticket:ticket-list")
    else:
        form = TicketForm()

    context = {
        'form':form,
        'departments' : departments,
    }
    return render(request,'ticket/add.html',context)

'''تیکت و پاسخ های آن'''
@login_required
def TicketDetail(request,id):       
    
    ticketdetail = Ticket.objects.get(id=id)
    response = Response.objects.filter(ticket=ticketdetail).order_by('-pb_date')
    
    context = {
        'ticketdetail':ticketdetail,
        'response':response,
       
    }

    return render(request,'ticket/detail.html',context)


@login_required
def AddResponse(request,id):        

    ticket = Ticket.objects.get(id=id)
    if request.method == "POST":
        form = ResponseForm(request.POST)
        if form.is_valid() and ticket.status :
            form = form.save(commit=False)
            form.user = request.user
            form.ticket = ticket
            form.save()
            return redirect("ticket:ticket-detail",id=id)
    else:
        form = ResponseForm()

    context = {
        'form':form,
    }
    return render(request,'ticket/response.html',context)

templates/ticket/partials/_footer.html
{% load static %}
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>&copy; 1400-1401 <a href="#">SalvatorLTE</a>.</strong>
    کلیه حقوق این سایت تو کتف آقای کوثری.
    <div class="float-right d-none d-sm-inline-block">
      <b>Deli</b>
    </div>
  </footer>

templates/ticket/partials/_header.html
{% load static %}


  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">

      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>

      <li class="nav-item d-none d-sm-inline-block">
        <a href="{%url 'ticket:homepage'%}" class="nav-link">خانه</a>
      </li>    

    </ul>

    <ul class="navbar-nav mr-auto-navbav">

      <li class="nav-item">
        <a href="{%url 'logout'%}" class="nav-link" >          
          <i class="fa fa-sign-out-alt"></i>
        </a>
      </li>

    </ul>
  </nav>
  
  <!-- /.navbar -->

templates/ticket/partials/_sidebar.html
 {% load static %}
 {% load gravatar %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
 
  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% gravatar_url user.email 150 %}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">
          {% if user.get_full_name %}
          {{user.get_full_name}}
        {% else %}
          {{user.username}}
        {% endif %}
      </a>              
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon fas fa-ticket-alt"></i>
            <p>
              تیکت
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{%url 'ticket:ticket-list' %}" class="nav-link ">
                <i class="fa fa-list nav-icon"></i>
                <p>لیست تیکت ها</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'ticket:ticket-add' %}" class="nav-link">
                <i class="fas fa-pen nav-icon"></i>
                <p>افزودن تیکت</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon 	fas fa-user-circle"></i>
            <p>
              پروفایل
              <i class="right fas fa-head-side-mask"></i>
            </p>
          </a>
        
            <li class="nav-item">
              <a href="#" class="nav-link ">
                <i class="fa fas fa-user-edit nav-icon"></i>
                <p>پروفایل</p>
              </a>
            </li>
            

        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

templates/ticket/partials/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>میزکاربر</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{%static 'ticket/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet"
    href="{%static 'ticket/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{%static 'ticket/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{%static 'ticket/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'ticket/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{%static 'ticket/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{%static 'ticket/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{%static 'ticket/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Bootstrap 4 RTL -->
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href="{%static 'ticket/dist/css/custom.css' %}">
</head>





<!-- Start header -->
{% include 'ticket/partials/_header.html' %}
<!-- End header -->

<!-- Start sidebar -->
{% include 'ticket/partials/_sidebar.html' %}
<!-- End sidebar -->

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">
                {% block title %}

                {% endblock title %}
              </h1>
            </div>
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
      <section class="content">
        <div class="container-fluid">

          {% block content %}

          {% endblock content %}
        </div>
      </section>
      <!-- /.card -->
    </div>
    <!-- ./wrapper -->
</body>

<!-- Start Footer -->
{% include 'ticket/partials/_footer.html' %}
<!-- End Footer -->


<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->


<!-- jQuery -->
<script src="{%static 'ticket/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{%static 'ticket/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{%static 'ticket/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{%static 'ticket/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{%static 'ticket/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{%static 'ticket/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{%static 'ticket/plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{%static 'ticket/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{%static 'ticket/plugins/moment/moment.min.js' %}"></script>
<script src="{%static 'ticket/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{%static 'ticket/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{%static 'ticket/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{%static 'ticket/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{%static 'ticket/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{%static 'ticket/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{%static 'ticket/dist/js/demo.js' %}"></script>
</body>

</html>