api/urls.py
from django.urls import path
from rest_framework.serializers import as_serializer_error
from .views import *
app_name = "api"

urlpatterns = [
    path('ticket/',TicketList.as_view(),name="list"),
    path('ticket/<int:pk>/',TicketDetail.as_view(),name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from account import views
from django.contrib.auth.views import  LogoutView
from config.settings import DEBUG
from django.conf import settings   
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Ticket
    path('ticket/', include('ticket.urls')),
    #Api
    path('api/', include('api.urls')),
    #Account
    path('account/', include('account.urls')),
    path('login/', views.Login, name="login"), 
    path('logout/', LogoutView.as_view(), name='logout'), 
    path('signup/', views.Signup, name="signup"),
]


if DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from . import views

app_name='ticket'

urlpatterns = [
    
    path('', views.Home, name="homepage"),
    # Ticket
    path('add/', views.AddTicket, name="ticket-add"),
    path('list/', views.TicketList, name="ticket-list"),
    path('detail/<int:id>', views.TicketDetail, name="ticket-detail"),
    # Response
    path('response/<int:id>', views.AddResponse, name="response-add"),

]

ticket/models.py
from django.db import models
from account.models import Department, User 
from datetime import datetime
from django.utils.translation import gettext as _
from extensions.utils import jalali_converter
# Create your models here.


class Ticket(models.Model):
    
    user = models.ForeignKey(User, verbose_name=_("کاربر"),default=None, on_delete=models.CASCADE)
    title = models.CharField(_("موضوع"), max_length=50)
    sup_type = models.ForeignKey(Department, verbose_name= _("دپارتمان"), on_delete=models.SET_NULL, blank=True,null=True)
    content = models.TextField(_("پیام"),blank=True,null=True)
    image = models.ImageField(_("عکس"), upload_to='media/ticket',blank=True,null=True)
    pb_date = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=False, default=datetime.now)
    status = models.BooleanField(_("وضعیت تیکت"),default=True)
    
    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"
        ordering = ['-pb_date']

    def __str__(self):
        return self.title
    def jpublish(self):
        return jalali_converter(self.pb_date)
    jpublish.short_description = "زمان انتشار"

class Response(models.Model):
    user = models.ForeignKey(User, verbose_name=_("کاربر"),default=None, on_delete=models.CASCADE)
    ticket = models.ForeignKey("Ticket", verbose_name=_("تیکت"),default=None, on_delete=models.CASCADE)
    content = models.TextField(_("پیام"),blank=True,null=True)
    image = models.ImageField(_("عکس"), upload_to='media/ticket',blank=True,null=True)
    pb_date = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=False, default=datetime.now)
    
    class Meta:
        verbose_name = "جواب"
        verbose_name_plural = "جواب ها"
        ordering = ['-pb_date']

    def jpublish(self):
        return jalali_converter(self.pb_date)
    jpublish.short_description = "زمان انتشار"
    

    def __str__(self):
        return self.content

ticket/forms.py
from django.db.models import fields
from django.db.models.base import Model
from .models import Ticket, Response
from django.forms import ModelForm
# class TicketForm(forms.Form):
#     STATUS_CHOICES = (
# 		('d', 'پشتیبانی'),
# 		('p', "حسابداری"),
# 	)
#     title = forms.CharField(label='Your name', max_length=100,required=True)
#     sup_type = forms.ChoiceField(choices=STATUS_CHOICES)
#     email = forms.EmailField(disabled=True,max_length=100, required=False)
#     content = forms.CharField(widget=forms.Textarea,required=True)


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        exclude = ['pb_date', 'status', 'user', 'response']


class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = ['content', 'image', ]

ticket/views.py
from django.shortcuts import render,redirect
from .models import Ticket, Response
from account.models import Department
from .forms import TicketForm,ResponseForm
from django.contrib.auth.decorators import login_required


@login_required
def Home(request):
    context = {}
    return render(request,'ticket/home.html',context)

'''لیست تیکت های کاربر یا پشتیبان'''
@login_required
def TicketList(request):    
    ticket_list = Ticket.objects.all()
    cus_tickets = Ticket.objects.filter(user=request.user)
    
    if request.user.is_supporter:
        sup_tickets = Ticket.objects.filter(sup_type=request.user.department)

    context = {
        'ticket_list': ticket_list,
        'sup_tickets':sup_tickets,
        'cus_tickets':cus_tickets,
    }
    return render(request,'ticket/list.html',context)


@login_required
def AddTicket(request):      
    departments = Department.objects.all()
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect("ticket:ticket-list")
    else:
        form = TicketForm()

    context = {
        'form':form,
        'departments' : departments,
    }
    return render(request,'ticket/add.html',context)

'''تیکت و پاسخ های آن'''
@login_required
def TicketDetail(request,id):       
    
    ticketdetail = Ticket.objects.get(id=id)
    response = Response.objects.filter(ticket=ticketdetail).order_by('-pb_date')
    
    context = {
        'ticketdetail':ticketdetail,
        'response':response,
       
    }

    return render(request,'ticket/detail.html',context)


@login_required
def AddResponse(request,id):        

    ticket = Ticket.objects.get(id=id)
    if request.method == "POST":
        form = ResponseForm(request.POST)
        if form.is_valid() and ticket.status :
            form = form.save(commit=False)
            form.user = request.user
            form.ticket = ticket
            form.save()
            return redirect("ticket:ticket-detail",id=id)
    else:
        form = ResponseForm()

    context = {
        'form':form,
    }
    return render(request,'ticket/response.html',context)

templates/ticket/add.html
{% extends 'ticket/partials/base.html' %}
{% load static %}
{% block title %}
افزودن تیکت     
{% endblock title %}

{% block content %}
  <!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12" >
          <!-- general form elements -->
          <div class="card card-primary">
           
            <div class="card-header">
              <h3 class="card-title">ایجاد تیکت</h3>
            </div>
            <!-- /.card-header -->

            <!-- form start -->
            <form action="" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
              <div class="card-body">
                <!-- <div class="form-group">
                  <label for="exampleInputEmail1">آدرس ایمیل</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" name='email' placeholder="ایمیل خود را وارد کنید...">
                </div> -->
                <div class="form-group">
                  <label>موضوع</label>
                  <input type="text" class="form-control" name="title" placeholder="موضوع تیکت را وارد کنید..." required>
                </div>  
                <div class="form-group">
                  <label>انتخاب دپارتمان</label>
                  <select class="form-control" name="sup_type" required>
                    <option value="">انتخاب کنید...</option>
                    {% for department in departments %}
                      <option value="{{department.id}}">{{department.name}}</option> 
                    {% endfor %}
                  </select>
                </div>
                <!-- textarea -->
                <div class="form-group">
                  <label>پیام</label>
                  <textarea class="form-control" rows="3" name="content" placeholder="پیام خود را وارد کنید" required></textarea>
                </div>
                <!-- <div class="form-group">
                  <label for="exampleInputFile">بارگذاری عکس</label>
                  <div class="input-group">
                    <div class="custom-file">
                      <input type="image" alt="" name="image" class="custom-file-input" id="exampleInputFile" placeholder="عکس خود را در صورت لزوم آپلود کنید">
                      <label class="custom-file-label" for="exampleInputFile">عکس خود را در صورت لزوم آپلود کنید</label>
                    </div>
                    <div class="input-group-append">
                      <span class="input-group-text" id="">آپلود</span>
                    </div>
                  </div>
                </div> -->
                <div class="form-check">
                  <label class="form-check-label" for="exampleCheck1">وضعیت تیکت</label>
                  <td><span class="alert alert-success">باز است</span></td>
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" value="submit" class="btn btn-primary">ثبت</button>
              </div>
            </form>

          </div>
          <!-- /.card -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
  <!-- ./wrapper -->




</div>
</body>
{% endblock content %}

templates/ticket/detail.html
{% extends 'ticket/partials/base.html' %}
{% load static %}

{% block title %}
تیکت شما
{% endblock title %}
    

{% block content %}
        <!-- Main content -->
            {% if not ticketdetail.status %}
            <div class="info-box mb-6 bg-warning">
                <span class="info-box-icon" ><i class="fas fa-exclamation-circle" ></i></span>
                <div class="info-box-content" style="text-align: center;">
      
                  <span class="info-box-text">این تیکت بسته شده است درصورت نیاز تیکت جدیدی ایجاد کنید</span>
                  <span class="info-box-number">SalvatorDeli</span>
                </div>
                <!-- /.info-box-content -->
            </div>
            {% endif %}
                
        <section class="content">
            <div class="container-fluid">
              <div class="row">
                <!-- left column -->
                <div class="col-md-8" >
                  <!-- general form elements -->
                  
                <!--  --------------------پاسخ های تیکت------------------ -->
                {% for response in response  %}
                    <div class="card card-primary" >
                    <!-- /.card-header -->
                        <div class="card-header" style="background-color: red;">
                            <h3 class="card-title">{{response.user.username}}</h3>
                            {{response.jpublish}}
                        </div> 
                    <!-- card-body -->
                        <div class="card-body">
                            <div class="form-group">
                                <p>{{response.content}}</p>
                            </div>                            
                        </div>
                    <!-- /.card-body -->                        
                        {% if response.ticket.status and forloop.first and response.user != request.user %}
                            <div class="card-footer">
                                <a href="{% url 'ticket:response-add' response.ticket.id %}"><button  class="btn btn-primary">پاسخ</button></a>
                            </div>                     
                        {% endif %}                                
                    </div>
                {% endfor %}
                <!--  --------------------/.پاسخ های تیکت------------------ -->  

             <!-- ----------------------- تیکت اصلی ------------------------>
                <div class="card card-primary">
                    <!-- card-header -->
                    <div class="card-header" style="background-color: black;">
                        <h3 class="card-title">تیکت</h3>
                            {{ticketdetail.jpublish}} -
                            {{ticketdetail.user.username}}
                    </div>
                        <!-- card-body -->
                        
                        <div class="card-body">
                           <div class="form-group">
                               <p>{{ticketdetail.content}}</p>
                           </div>
                           
                           
                           
                        </div>
                        <div class="card-footer">
                            <div class="form-check">
                                <label class="form-check-label" for="exampleCheck1">وضعیت تیکت</label>
                                
                                {% if ticketdetail.status %}
                                <span class="alert alert-success">باز است</span>                              
                                {% else %}
                                <span class="alert alert-danger">بسته است</span>
                                {% endif %}
                                
                                {% if  response.count == 0 and request.user.department or request.user.is_superuser %}
                                     <a href="{% url 'ticket:response-add' ticketdetail.id %}"><button  class="btn btn-primary">پاسخ</button></a>
                                {% endif %}
                        
                        </div>
                        <!-- /.card -->
                        </div>
                </div>
        <!-- -----------------------/. تیکت اصلی ------------------------>             
                </div>
            <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
                               
                           
                           

{% endblock content %} 

templates/ticket/home.html
{% extends 'ticket/partials/base.html' %}
{% load static %}

{% block title %}
خانه 
{% endblock title %}
  

{% block content %}
      <!-- Main content -->
      <div class="container-fluid">
        <div class="info-box mb-6 bg-warning">
          <span class="info-box-icon"><i class="fas fa-envelope-open"></i></span>

          <div class="info-box-content" style="text-align: center;">
            <span class="info-box-text">به سیستم تیکتینگ دلی خوش آمدید</span>
            <span class="info-box-number">SalvatorDeli</span>
          </div>
          <!-- /.info-box-content -->
        </div>
      </div>
{% endblock content %}

templates/ticket/list.html
{% extends 'ticket/partials/base.html' %}
{% load static %}

{% block title %}
لیست تیکت ها    
{% endblock title %}

{% block content %}
        <!-- Main content -->
            <div class="container-fluid">
                <!-- /.row -->
            <div class="row">
                <div class="col-12">
                <div class="card">
                    <div class="card-header">
                    <h3 class="card-title">...</h3>
            
                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
            
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default">
                            <i class="fas fa-search"></i>
                            </button>
                        </div>
                        </div>
                    </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                        <thead>
                        <tr>
                            <th>شماره</th>
                            <th>کاربر</th>
                            <th>تاریخ</th>
                            <th>توضیحات</th>
                            <th>وضعیت تیکت</th>
                        </tr>
                        </thead>

                        <tbody>
                            
                            {% if user.is_superuser %}                            
                                {% for ticket in ticket_list  %}
                                    <tr>
                                        <td>
                                            <a href="{%url 'ticket:ticket-detail' ticket.id %}"><button  class="btn btn-primary">{{ticket.id}}</button></a>
                                        </td>
                                        <td>{{ticket.user.first_name}}</td>
                                        <td>{{ticket.jpublish}}</td>
                                        <td>{{ticket.content|striptags|truncatewords:"10"}}</td>
                                        
                                        {% if ticket.status %}
                                            <td><span class="alert alert-success" >باز است</span></td>
                                        {% else %} 
                                            <td><span class="alert alert-danger">بسته است</span></td>
                                        {% endif %}                                            
                                    </tr>
                                    {% empty %}
                                        <td><b>در حال حاضر تیکتی وجود ندارد</b></td>
                                {% endfor %}                                    
                            
                                                           
                            {% elif user.is_supporter %}
                                {% for ticket in sup_tickets %}
                                
                                    <tr>
                                        <td>
                                            <a href="{%url 'ticket:ticket-detail' ticket.id %}"><button  class="btn btn-primary">{{ticket.id}}</button></a>
                                        </td>
                                        <td>{{ticket.user.first_name}}</td>
                                        <td>{{ticket.jpublish}}</td>
                                        <td>{{ticket.content|striptags|truncatewords:"10"}}</td>
                                        
                                        {% if ticket.status %}
                                            <td><span class="alert alert-success" >باز است</span></td>
                                        {% else %} 
                                            <td><span class="alert alert-danger">بسته است</span></td>
                                        {% endif %}                                            
                                    </tr>
                                    {% empty %}
                                        <td><b>در حال حاضر تیکتی وجود ندارد</b></td>
                                
                                {% endfor %} 

                            {% else %}                                
                                {% for ticket in cus_tickets  %}
                                    <tr>                                                              
                                        <td>
                                            <a href="{%url 'ticket:ticket-detail' ticket.id %}"><button  class="btn btn-primary">{{ticket.id}}</button></a> 
                                        </td>                                          
                                        <td>{{ticket.user.first_name}}</td>                                    
                                        <td>{{ticket.jpublish}}</td>
                                        <td>{{ticket.content|striptags|truncatewords:"10"}}</td>
                                            
                                        {% if ticket.status %}
                                            <td><span class="alert alert-success">باز است</span></td>
                                        {% else %} 
                                            <td><span class="alert alert-danger">بسته است</span></td>
                                        {% endif %}                                        
                                    </tr>
                                    {% empty %}
                                        <td><b>در حال حاضر تیکتی وجود ندارد</b></td>
                                {% endfor %}                                 
                                
                            {% endif %}
                                              
                        </tbody>
                    </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                </div>
                </div>
            <!-- /.row -->
            </div>


{% endblock content %}

templates/ticket/response.html
{% extends 'ticket/partials/base.html' %}
{% load static %}

{% block title %}
ثبت پاسخ
{% endblock title %}


{% block content %}
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-8" >
          <!-- general form elements -->
          <div class="card card-primary">
           
            <div class="card-header">
              <h3 class="card-title">ایجاد تیکت</h3>
            </div>
            <!-- /.card-header -->

            <!-- form start -->
            <form action="" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
              <div class="card-body">
                <!-- textarea -->
                <div class="form-group">
                  <label>پیام</label>
                  <textarea class="form-control" rows="3" name="content" placeholder="پیام خود را وارد کنید" required></textarea>
                </div>
                <!-- <div class="form-group">
                  <label for="exampleInputFile">بارگذاری عکس</label>
                  <div class="input-group">
                    <div class="custom-file">
                      <input type="image" alt="" name="image" class="custom-file-input" id="exampleInputFile" placeholder="عکس خود را در صورت لزوم آپلود کنید">
                      <label class="custom-file-label" for="exampleInputFile">عکس خود را در صورت لزوم آپلود کنید</label>
                    </div>
                    <div class="input-group-append">
                      <span class="input-group-text" id="">آپلود</span>
                    </div>
                  </div>
                </div> -->
               
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" value="submit" class="btn btn-primary">ثبت</button>
              </div>
            </form>

          </div>
          <!-- /.card -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
  
{% endblock content %}